name: Python Code Quality Check (CI)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Lay code moi nhat tu kho ve may ao
        uses: actions/checkout@v3

      - name: Cai dat phien ban Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Tu dong chay bo kiem thu Unit Test
        run: python -m unittest test_main.py